/** Every label the admin screens show, in both interface languages. */
export const adminStrings = {
  en: {
    'app.title': 'Site admin',
    'app.public': 'View the site',
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'Profile',
    'nav.journey': 'Journey',
    'nav.projects': 'Projects',
    'nav.lists': 'Lists',
    'nav.media': 'Media',
    'nav.cv': 'CV',
    'nav.seo': 'SEO',
    'lang.switch': 'العربية',
    'action.save': 'Save',
    'action.reset': 'Undo changes',
    'action.add': 'Add',
    'action.delete': 'Delete',
    'action.cancel': 'Cancel',
    'action.retry': 'Try again',
    'action.edit': 'Edit',
    'action.close': 'Close',
    'action.choose': 'Choose',
    'action.clear': 'Clear',
    'action.up': 'Move up',
    'action.down': 'Move down',
    'state.saving': 'Saving…',
    'state.saved': 'Saved',
    'state.unsaved': 'Unsaved changes',
    'state.clean': 'No changes',
    'state.loading': 'Loading…',
    'state.empty': 'Nothing here yet',
    'error.session': 'Your session has ended. Sign in again to continue.',
    'error.generic': 'Something went wrong.',
    'error.load': 'This could not be loaded.',
    'error.notFound': 'This is not a page.',
    'confirm.question': 'Delete this for good?',
    'guard.leave': 'You have unsaved changes. Leave anyway?',
    'field.english': 'English',
    'field.arabic': 'Arabic',
    'field.visible': 'Shown on the site',
    'field.none': 'None',
  },
  ar: {
    'app.title': 'إدارة الموقع',
    'app.public': 'عرض الموقع',
    'nav.dashboard': 'اللوحة',
    'nav.profile': 'الملف الشخصي',
    'nav.journey': 'المسيرة',
    'nav.projects': 'المشاريع',
    'nav.lists': 'القوائم',
    'nav.media': 'الوسائط',
    'nav.cv': 'السيرة الذاتية',
    'nav.seo': 'تهيئة محركات البحث',
    'lang.switch': 'English',
    'action.save': 'حفظ',
    'action.reset': 'تراجع عن التغييرات',
    'action.add': 'إضافة',
    'action.delete': 'حذف',
    'action.cancel': 'إلغاء',
    'action.retry': 'إعادة المحاولة',
    'action.edit': 'تعديل',
    'action.close': 'إغلاق',
    'action.choose': 'اختيار',
    'action.clear': 'إزالة',
    'action.up': 'تحريك لأعلى',
    'action.down': 'تحريك لأسفل',
    'state.saving': 'جارٍ الحفظ…',
    'state.saved': 'تم الحفظ',
    'state.unsaved': 'تغييرات غير محفوظة',
    'state.clean': 'لا تغييرات',
    'state.loading': 'جارٍ التحميل…',
    'state.empty': 'لا يوجد شيء بعد',
    'error.session': 'انتهت الجلسة. سجّل الدخول مرة أخرى للمتابعة.',
    'error.generic': 'حدث خطأ ما.',
    'error.load': 'تعذّر التحميل.',
    'error.notFound': 'هذه ليست صفحة.',
    'confirm.question': 'حذف هذا نهائياً؟',
    'guard.leave': 'لديك تغييرات غير محفوظة. هل تريد المغادرة؟',
    'field.english': 'الإنجليزية',
    'field.arabic': 'العربية',
    'field.visible': 'ظاهر في الموقع',
    'field.none': 'لا شيء',
  },
} as const;

export type AdminStringKey = keyof typeof adminStrings.en;
export type AdminLang = keyof typeof adminStrings;
