// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Profile.Api.Data;

#nullable disable

namespace Profile.Api.Data.Migrations
{
    [DbContext(typeof(ProfileContext))]
    [Migration("20260915201024_Admin")]
    partial class Admin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Profile.Api.Data.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Profile.Api.Data.CvFile", b =>
                {
                    b.Property<string>("Lang")
                        .HasColumnType("text");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Lang");

                    b.ToTable("CvFiles");
                });

            modelBuilder.Entity("Profile.Api.Data.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("Profile.Api.Data.JourneyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seniority")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("JourneyEntries");
                });

            modelBuilder.Entity("Profile.Api.Data.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("Profile.Api.Data.MediaRendition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaId", "Width")
                        .IsUnique();

                    b.ToTable("MediaRenditions");
                });

            modelBuilder.Entity("Profile.Api.Data.PageSeo", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<Guid?>("ShareMediaId")
                        .HasColumnType("uuid");

                    b.HasKey("Key");

                    b.HasIndex("ShareMediaId");

                    b.ToTable("PageSeo");
                });

            modelBuilder.Entity("Profile.Api.Data.ProfileRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHubUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("HeroMediaId")
                        .HasColumnType("uuid");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PortraitMediaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HeroMediaId");

                    b.HasIndex("PortraitMediaId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Profile.Api.Data.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CoverMediaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CoverMediaId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Profile.Api.Data.ProjectSlugRedirect", b =>
                {
                    b.Property<string>("OldSlug")
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("OldSlug");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectSlugRedirects");
                });

            modelBuilder.Entity("Profile.Api.Data.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("GaMeasurementId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GaPropertyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MessageRetentionDays")
                        .HasColumnType("integer");

                    b.Property<string>("NotificationEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchConsoleToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("Profile.Api.Data.SpokenLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SpokenLanguages");
                });

            modelBuilder.Entity("Profile.Api.Data.Technology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Technologies");
                });

            modelBuilder.Entity("Profile.Api.Data.Certificate", b =>
                {
                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<int>("CertificateId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CertificateId");

                            b1.ToTable("Certificates");

                            b1.WithOwner()
                                .HasForeignKey("CertificateId");
                        });

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Api.Data.Education", b =>
                {
                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Degree", b1 =>
                        {
                            b1.Property<int>("EducationId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EducationId");

                            b1.ToTable("Education");

                            b1.WithOwner()
                                .HasForeignKey("EducationId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Institution", b1 =>
                        {
                            b1.Property<int>("EducationId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EducationId");

                            b1.ToTable("Education");

                            b1.WithOwner()
                                .HasForeignKey("EducationId");
                        });

                    b.Navigation("Degree")
                        .IsRequired();

                    b.Navigation("Institution")
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Api.Data.JourneyEntry", b =>
                {
                    b.OwnsMany("Profile.Api.Data.Highlight", "Highlights", b1 =>
                        {
                            b1.Property<int>("JourneyEntryId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("integer");

                            b1.HasKey("JourneyEntryId", "Id");

                            b1.ToTable("JourneyHighlights", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JourneyEntryId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Organisation", b1 =>
                        {
                            b1.Property<int>("JourneyEntryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("JourneyEntryId");

                            b1.ToTable("JourneyEntries");

                            b1.WithOwner()
                                .HasForeignKey("JourneyEntryId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Summary", b1 =>
                        {
                            b1.Property<int>("JourneyEntryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("JourneyEntryId");

                            b1.ToTable("JourneyEntries");

                            b1.WithOwner()
                                .HasForeignKey("JourneyEntryId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<int>("JourneyEntryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("JourneyEntryId");

                            b1.ToTable("JourneyEntries");

                            b1.WithOwner()
                                .HasForeignKey("JourneyEntryId");
                        });

                    b.Navigation("Highlights");

                    b.Navigation("Organisation")
                        .IsRequired();

                    b.Navigation("Summary")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Api.Data.Media", b =>
                {
                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Alt", b1 =>
                        {
                            b1.Property<Guid>("MediaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("MediaId");

                            b1.ToTable("Media");

                            b1.WithOwner()
                                .HasForeignKey("MediaId");
                        });

                    b.Navigation("Alt")
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Api.Data.MediaRendition", b =>
                {
                    b.HasOne("Profile.Api.Data.Media", null)
                        .WithMany("Renditions")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Api.Data.PageSeo", b =>
                {
                    b.HasOne("Profile.Api.Data.Media", null)
                        .WithMany()
                        .HasForeignKey("ShareMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<string>("PageSeoKey")
                                .HasColumnType("text");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PageSeoKey");

                            b1.ToTable("PageSeo");

                            b1.WithOwner()
                                .HasForeignKey("PageSeoKey");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<string>("PageSeoKey")
                                .HasColumnType("text");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PageSeoKey");

                            b1.ToTable("PageSeo");

                            b1.WithOwner()
                                .HasForeignKey("PageSeoKey");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Api.Data.ProfileRecord", b =>
                {
                    b.HasOne("Profile.Api.Data.Media", null)
                        .WithMany()
                        .HasForeignKey("HeroMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Profile.Api.Data.Media", null)
                        .WithMany()
                        .HasForeignKey("PortraitMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "About", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Eyebrow", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Headline", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "HeroSubtitle", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "HeroTitle", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Location", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Quote", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Summary", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.Navigation("About")
                        .IsRequired();

                    b.Navigation("Eyebrow")
                        .IsRequired();

                    b.Navigation("Headline")
                        .IsRequired();

                    b.Navigation("HeroSubtitle")
                        .IsRequired();

                    b.Navigation("HeroTitle")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Quote")
                        .IsRequired();

                    b.Navigation("Summary")
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Api.Data.Project", b =>
                {
                    b.HasOne("Profile.Api.Data.Media", null)
                        .WithMany()
                        .HasForeignKey("CoverMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Body", b1 =>
                        {
                            b1.Property<int>("ProjectId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Summary", b1 =>
                        {
                            b1.Property<int>("ProjectId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<int>("ProjectId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("Body")
                        .IsRequired();

                    b.Navigation("Summary")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Api.Data.ProjectSlugRedirect", b =>
                {
                    b.HasOne("Profile.Api.Data.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Api.Data.SpokenLanguage", b =>
                {
                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Level", b1 =>
                        {
                            b1.Property<int>("SpokenLanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SpokenLanguageId");

                            b1.ToTable("SpokenLanguages");

                            b1.WithOwner()
                                .HasForeignKey("SpokenLanguageId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<int>("SpokenLanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SpokenLanguageId");

                            b1.ToTable("SpokenLanguages");

                            b1.WithOwner()
                                .HasForeignKey("SpokenLanguageId");
                        });

                    b.Navigation("Level")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Api.Data.Technology", b =>
                {
                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Category", b1 =>
                        {
                            b1.Property<int>("TechnologyId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TechnologyId");

                            b1.ToTable("Technologies");

                            b1.WithOwner()
                                .HasForeignKey("TechnologyId");
                        });

                    b.Navigation("Category")
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Api.Data.Media", b =>
                {
                    b.Navigation("Renditions");
                });
#pragma warning restore 612, 618
        }
    }
}
