// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Profile.Api.Data;

#nullable disable

namespace Profile.Api.Data.Migrations
{
    [DbContext(typeof(ProfileContext))]
    partial class ProfileContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Profile.Api.Data.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Profile.Api.Data.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("Profile.Api.Data.JourneyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seniority")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("JourneyEntries");
                });

            modelBuilder.Entity("Profile.Api.Data.ProfileRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHubUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Profile.Api.Data.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Profile.Api.Data.SpokenLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SpokenLanguages");
                });

            modelBuilder.Entity("Profile.Api.Data.Technology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Technologies");
                });

            modelBuilder.Entity("Profile.Api.Data.Certificate", b =>
                {
                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<int>("CertificateId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CertificateId");

                            b1.ToTable("Certificates");

                            b1.WithOwner()
                                .HasForeignKey("CertificateId");
                        });

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Api.Data.Education", b =>
                {
                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Degree", b1 =>
                        {
                            b1.Property<int>("EducationId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EducationId");

                            b1.ToTable("Education");

                            b1.WithOwner()
                                .HasForeignKey("EducationId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Institution", b1 =>
                        {
                            b1.Property<int>("EducationId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EducationId");

                            b1.ToTable("Education");

                            b1.WithOwner()
                                .HasForeignKey("EducationId");
                        });

                    b.Navigation("Degree")
                        .IsRequired();

                    b.Navigation("Institution")
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Api.Data.JourneyEntry", b =>
                {
                    b.OwnsMany("Profile.Api.Data.Highlight", "Highlights", b1 =>
                        {
                            b1.Property<int>("JourneyEntryId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("integer");

                            b1.HasKey("JourneyEntryId", "Id");

                            b1.ToTable("JourneyHighlights", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JourneyEntryId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Organisation", b1 =>
                        {
                            b1.Property<int>("JourneyEntryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("JourneyEntryId");

                            b1.ToTable("JourneyEntries");

                            b1.WithOwner()
                                .HasForeignKey("JourneyEntryId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Summary", b1 =>
                        {
                            b1.Property<int>("JourneyEntryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("JourneyEntryId");

                            b1.ToTable("JourneyEntries");

                            b1.WithOwner()
                                .HasForeignKey("JourneyEntryId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<int>("JourneyEntryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("JourneyEntryId");

                            b1.ToTable("JourneyEntries");

                            b1.WithOwner()
                                .HasForeignKey("JourneyEntryId");
                        });

                    b.Navigation("Highlights");

                    b.Navigation("Organisation")
                        .IsRequired();

                    b.Navigation("Summary")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Api.Data.ProfileRecord", b =>
                {
                    b.OwnsOne("Profile.Api.Data.LocalizedText", "About", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Eyebrow", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Headline", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "HeroSubtitle", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "HeroTitle", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Location", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Quote", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Summary", b1 =>
                        {
                            b1.Property<int>("ProfileRecordId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProfileRecordId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileRecordId");
                        });

                    b.Navigation("About")
                        .IsRequired();

                    b.Navigation("Eyebrow")
                        .IsRequired();

                    b.Navigation("Headline")
                        .IsRequired();

                    b.Navigation("HeroSubtitle")
                        .IsRequired();

                    b.Navigation("HeroTitle")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Quote")
                        .IsRequired();

                    b.Navigation("Summary")
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Api.Data.Project", b =>
                {
                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Body", b1 =>
                        {
                            b1.Property<int>("ProjectId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Summary", b1 =>
                        {
                            b1.Property<int>("ProjectId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<int>("ProjectId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("Body")
                        .IsRequired();

                    b.Navigation("Summary")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Api.Data.SpokenLanguage", b =>
                {
                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Level", b1 =>
                        {
                            b1.Property<int>("SpokenLanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SpokenLanguageId");

                            b1.ToTable("SpokenLanguages");

                            b1.WithOwner()
                                .HasForeignKey("SpokenLanguageId");
                        });

                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<int>("SpokenLanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SpokenLanguageId");

                            b1.ToTable("SpokenLanguages");

                            b1.WithOwner()
                                .HasForeignKey("SpokenLanguageId");
                        });

                    b.Navigation("Level")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Profile.Api.Data.Technology", b =>
                {
                    b.OwnsOne("Profile.Api.Data.LocalizedText", "Category", b1 =>
                        {
                            b1.Property<int>("TechnologyId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TechnologyId");

                            b1.ToTable("Technologies");

                            b1.WithOwner()
                                .HasForeignKey("TechnologyId");
                        });

                    b.Navigation("Category")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
